[project]
name = "noaa-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.14",
    "aiolimiter>=1.2.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.13",
]
